"""add worker_agent_ids to agents

Revision ID: 827237e1064f
Revises: 17d21b681f28
Create Date: 2026-07-22 15:29:09.519910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827237e1064f'
down_revision: Union[str, None] = '17d21b681f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('worker_agent_ids', sa.JSON(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'worker_agent_ids')
    # ### end Alembic commands ###
